on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  deploy-render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - env:
          deploy-url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl "$deploy_url"